#
# Makefile for the vibrator driver ICs with vibrator driver
#

obj-$(CONFIG_MOTOR_DRV_MAX77803)	+= max77803_haptic.o
obj-$(CONFIG_HAPTIC_ISA1200)			+= haptic_isa1200.o
obj-$(CONFIG_HAPTIC_ISA1400)			+= haptic_isa1400.o
