/* linux/arch/arm/mach-exynos/board-klimt-gpio.c
 *
 * Copyright (c) 2013 Samsung Electronics Co., Ltd.
 *		http://www.samsung.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#include <linux/gpio.h>
#include <plat/gpio-cfg.h>
#include <asm/system_info.h>

#ifdef CONFIG_SEC_GPIO_DVS
#include <linux/secgpio_dvs.h>
#endif

#define GPIO_LV_L	0	/* GPIO level low */
#define GPIO_LV_H	1	/* GPIO level high */
#define GPIO_LV_N	2	/* GPIO level none */
/*
======================================================
klimt revision history from system_rev
======================================================
*/

struct gpio_init_data {
	u32 num;
	u32 cfg;
	u32 val;
	u32 pud;
};

struct gpio_sleep_data {
	u32 num;
	u32 cfg;
	u32 pud;
};

struct sleep_gpio_tables {
	struct gpio_sleep_data *table;
	u32 arr_size;
};

#define MAX_BOARD_REV	0xf
static struct sleep_gpio_tables klimt_sleep_gpio_tables[MAX_BOARD_REV];
static int nr_klimt_sleep_gpio_table;

/* init gpio table for KLIMT project */
static struct gpio_init_data __initdata init_gpio_table[] = {
    /* GPA 0 */
	{ EXYNOS5420_GPA0(0), S3C_GPIO_SFN(2), GPIO_LV_N, S3C_GPIO_PULL_NONE },	/* BT_UART_RXD */
	{ EXYNOS5420_GPA0(2), S3C_GPIO_SFN(2), GPIO_LV_N, S3C_GPIO_PULL_NONE },	/* BT_UART_CTS */
#if defined(CONFIG_KLIMT_TD)
	{ EXYNOS5420_GPA0(4), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPA0(5), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPA0(6), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPA0(7), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
#endif
    /* GPA 1 */
	{ EXYNOS5420_GPA1(2), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* SENSOR_I2C_SDA */
	{ EXYNOS5420_GPA1(3), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* SENSOR_I2C_SCL */
    /* GPA 2 */
#if !defined(CONFIG_KLIMT_WIFI)
	{ EXYNOS5420_GPA2(0), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE },	/* GRIP_SDA */
	{ EXYNOS5420_GPA2(1), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE },	/* GRIP_SCL */
#endif
	{ EXYNOS5420_GPA2(4), S3C_GPIO_OUTPUT, GPIO_LV_L, S3C_GPIO_PULL_NONE },	/* GPIO_BTP_SPI_CLK */
	{ EXYNOS5420_GPA2(5), S3C_GPIO_OUTPUT, GPIO_LV_L, S3C_GPIO_PULL_NONE },	/* GPIO_BTP_SPI_CS_N */
	{ EXYNOS5420_GPA2(6), S3C_GPIO_INPUT, GPIO_LV_L, S3C_GPIO_PULL_DOWN },	/* GPIO_BTP_SPI_MISO */
	{ EXYNOS5420_GPA2(7), S3C_GPIO_OUTPUT, GPIO_LV_L, S3C_GPIO_PULL_NONE },	/* GPIO_BTP_SPI_MOSI */
    /* GPB 0 */
    /* GPB 1 */
    /* GPB 2 */
    /* GPB 3 */
	{ EXYNOS5420_GPB3(0), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* TSP_SDA_1.8V */
	{ EXYNOS5420_GPB3(1), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* TSP_SDA_1.8V */
	{ EXYNOS5420_GPB3(4), S3C_GPIO_OUTPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* MEM_LDO_SCL */
	{ EXYNOS5420_GPB3(5), S3C_GPIO_OUTPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* MEM_LDO_SDA */
    /* GPC 0 */	
	{ EXYNOS5420_GPC0(3), S3C_GPIO_SFN(2), GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* NAND_D(0) */
	{ EXYNOS5420_GPC0(4), S3C_GPIO_SFN(2), GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* NAND_D(1) */
	{ EXYNOS5420_GPC0(5), S3C_GPIO_SFN(2), GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* NAND_D(2) */
	{ EXYNOS5420_GPC0(6), S3C_GPIO_SFN(2), GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* NAND_D(3) */
    /* GPC 1 */
	{ EXYNOS5420_GPC1(0), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* WLAN_SDIO_CLK */
	{ EXYNOS5420_GPC1(1), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* WLAN_SDIO_CMD */
#if defined(CONFIG_KLIMT_TD)
	{ EXYNOS5420_GPC1(2), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
#endif
	{ EXYNOS5420_GPC1(3), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* WLAN_SDIO_D(0) */
	{ EXYNOS5420_GPC1(4), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* WLAN_SDIO_D(1) */
	{ EXYNOS5420_GPC1(5), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* WLAN_SDIO_D(2) */
	{ EXYNOS5420_GPC1(6), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* WLAN_SDIO_D(3) */
	{ EXYNOS5420_GPC1(7), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
    /* GPC 2 */
	{ EXYNOS5420_GPC2(2), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
    /* GPC 3 */
	{ EXYNOS5420_GPC3(0), S3C_GPIO_SFN(2), GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* NAND_D(4) */
	{ EXYNOS5420_GPC3(1), S3C_GPIO_SFN(2), GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* NAND_D(5) */
	{ EXYNOS5420_GPC3(2), S3C_GPIO_SFN(2), GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* NAND_D(6) */
	{ EXYNOS5420_GPC3(3), S3C_GPIO_SFN(2), GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* NAND_D(7) */
    /* GPC 4 */
	{ EXYNOS5420_GPC4(0), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPC4(1), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
    /* GPD 1 */
	{ EXYNOS5420_GPD1(1), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
#if defined(CONFIG_KLIMT_WIFI)
	{ EXYNOS5420_GPD1(2), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC(PDA_ACTIVE) */
#endif
    /* GPE 0 */
    /* GPE 1 */
	{ EXYNOS5420_GPE1(1), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
    /* GPF 0 */
    /* GPF 1 */
	{ EXYNOS5420_GPF1(4), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPF1(5), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPF1(6), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPF1(7), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
    /* GPG 0 */
	{ EXYNOS5420_GPG0(0), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
#if defined(CONFIG_KLIMT_WIFI)
	{ EXYNOS5420_GPG0(4), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC(CP_CMU_RST) */
#endif
    /* GPG 1 */
#if defined(CONFIG_KLIMT_WIFI)
	{ EXYNOS5420_GPG1(0), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC(IPC_SLAVE_WAKEUP) */
	{ EXYNOS5420_GPG1(1), S3C_GPIO_OUTPUT, GPIO_LV_L,  S3C_GPIO_PULL_NONE}, /* TSP_RST */
	{ EXYNOS5420_GPG1(3), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC(SUSPEND_REQUEST_HSIC) */
	{ EXYNOS5420_GPG1(4), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC(CP_ON) */
#endif
#if defined(CONFIG_KLIMT_WIFI)
	{ EXYNOS5420_GPG1(6), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC(AP_DUMP_INT) */
	{ EXYNOS5420_GPG1(7), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC(ACTIVE_STATE_HSIC) */
#endif
    /* GPG 2 */
	{ EXYNOS5420_GPG2(0), S3C_GPIO_OUTPUT, GPIO_LV_H, S3C_GPIO_PULL_NONE }, /* GPIO_M_RST_N */
    /* GPH 0 */
    /* GPJ 4 */
#if defined(CONFIG_KLIMT_WIFI)
	{ EXYNOS5420_GPJ4(1), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC(RESET_REQ_N) */
#endif
    /* GPX 0 */
#if defined(CONFIG_KLIMT_WIFI)
	{ EXYNOS5420_GPX0(4), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
#else
	{ EXYNOS5420_GPX0(4), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* GRIP_DET_AP */
#endif
	{ EXYNOS5420_GPX0(6), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* GPIO_ACC_INT2 */
	{ EXYNOS5420_GPX0(7), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_UP }, /* BTP_IRQ */
    /* GPX 1 */
#if defined(CONFIG_KLIMT_WIFI)
	{ EXYNOS5420_GPX1(2), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC(IPC_HOST_WAKEUP) */
#endif
	{ EXYNOS5420_GPX1(3), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* GPIO_ACC_INT1 */
	{ EXYNOS5420_GPX1(5), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* FUEL_ALERT */
    /* GPX 2 */
	{ EXYNOS5420_GPX2(0), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* WLAN_HOST_WAKE */
	{ EXYNOS5420_GPX2(5), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* GPIO_CODEC_IRQ_N */
 #if defined(CONFIG_KLIMT_WIFI)
	{ EXYNOS5420_GPX2(6), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC(CP_DUMP_INT) */
	{ EXYNOS5420_GPX2(7), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC(HSPA_ACTIVE) */
#endif
   /* GPX 3 */
	{ EXYNOS5420_GPX3(0), S3C_GPIO_SFN(0xF), GPIO_LV_N, S3C_GPIO_PULL_UP }, /* AP_PMIC_IRQ */
	{ EXYNOS5420_GPX3(1), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPX3(3), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPX3(4), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* GPIO_GYRO_DRDY */
#if defined(CONFIG_SENSORS_TMD3782)
	{ EXYNOS5420_GPX3(5), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* PS_ALS_INT */
#else
	{ EXYNOS5420_GPX3(5), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
#endif
    /* GPY 0 */
	{ EXYNOS5420_GPY0(0), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY0(1), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_NONE }, /* OCP_FLAG */
	{ EXYNOS5420_GPY0(2), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY0(3), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY0(4), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY0(5), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
    /* GPY 1 */
	{ EXYNOS5420_GPY1(0), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY1(1), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY1(2), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY1(3), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
    /* GPY 2 */
	{ EXYNOS5420_GPY2(1), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY2(2), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY2(3), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY2(4), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY2(5), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
    /* GPY 3 */
	{ EXYNOS5420_GPY3(3), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY3(4), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY3(5), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY3(6), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY3(7), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
    /* GPY 4 */
	{ EXYNOS5420_GPY4(0), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY4(1), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY4(2), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY4(3), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY4(4), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY4(5), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY4(6), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY4(7), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
    /* GPY 5 */
	{ EXYNOS5420_GPY5(0), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY5(1), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY5(2), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY5(3), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY5(4), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY5(5), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY5(6), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY5(7), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
    /* GPY 6 */
	{ EXYNOS5420_GPY6(0), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY6(1), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY6(2), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY6(3), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY6(4), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY6(5), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY6(6), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
	{ EXYNOS5420_GPY6(7), S3C_GPIO_INPUT, GPIO_LV_N, S3C_GPIO_PULL_DOWN }, /* NC */
    /* GPY 7 */
	{ EXYNOS5420_GPY7(4), S3C_GPIO_OUTPUT, GPIO_LV_L, S3C_GPIO_PULL_DOWN }, /* BTP_LDO_EN_3.3V */
	{ EXYNOS5420_GPY7(5), S3C_GPIO_OUTPUT, GPIO_LV_L, S3C_GPIO_PULL_DOWN }, /* BTP_LDO_EN_1.8V */
	{ EXYNOS5420_GPY7(6), S3C_GPIO_OUTPUT, GPIO_LV_L, S3C_GPIO_PULL_DOWN }, /* BTP_RST_N */
};

/* Sleep GPIO table for old HW revisions */
static struct gpio_sleep_data sleep_gpio_table_rev00[] = {
};

/* Latest : Rev0.9(3G) Rev0.6(WIFI) */
static struct gpio_sleep_data sleep_gpio_table_latest[] = {
    /* GPA 0 */
	{ EXYNOS5420_GPA0(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },	/* BT_UART_RXD */
	{ EXYNOS5420_GPA0(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UP_ENABLE },	/* BT_UART_TXD */
	{ EXYNOS5420_GPA0(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },	/* BT_UART_CTS */
	{ EXYNOS5420_GPA0(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UP_ENABLE },	/* BT_UART_RTS */
#if !defined(CONFIG_KLIMT_TD)
	{ EXYNOS5420_GPA0(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UP_ENABLE },	/* GPS_UART_RXD */
	{ EXYNOS5420_GPA0(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UP_ENABLE },	/* GPS_UART_TXD */
	{ EXYNOS5420_GPA0(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* GPS_UART_CTS */
	{ EXYNOS5420_GPA0(7), S5P_GPIO_PD_OUTPUT1, S5P_GPIO_PD_UPDOWN_DISABLE },/* GPS_UART_RTS */
#else
	{ EXYNOS5420_GPA0(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* NC */
	{ EXYNOS5420_GPA0(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* NC */
	{ EXYNOS5420_GPA0(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* NC */
	{ EXYNOS5420_GPA0(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* NC */
#endif
    /* GPA 1 */
	{ EXYNOS5420_GPA1(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* AP_RXD */
	{ EXYNOS5420_GPA1(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* AP_TXD */
	{ EXYNOS5420_GPA1(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },	/* SENSOR_I2C_SDA */
	{ EXYNOS5420_GPA1(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },	/* SENSOR_I2C_SCL */
	{ EXYNOS5420_GPA1(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* VT_CAM_SDA_1.8V */
	{ EXYNOS5420_GPA1(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* VT_CAM_SCL_1.8V */
    /* GPA 2 */
#if defined(CONFIG_KLIMT_WIFI)
	{ EXYNOS5420_GPA2(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPA2(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
#else
	{ EXYNOS5420_GPA2(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* GRIP_SDA */
	{ EXYNOS5420_GPA2(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* GRIP_SCL */
#endif
	{ EXYNOS5420_GPA2(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* 8M_EEPROM_SDA_1.8V */
	{ EXYNOS5420_GPA2(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* 8M_EEPROM_SCL_1.8V */
	{ EXYNOS5420_GPA2(4), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },	/* GPIO_BTP_SPI_CLK */
	{ EXYNOS5420_GPA2(5), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },	/* GPIO_BTP_SPI_CS_N */
	{ EXYNOS5420_GPA2(6), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_DOWN_ENABLE },	/* GPIO_BTP_SPI_MISO */
	{ EXYNOS5420_GPA2(7), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },	/* GPIO_BTP_SPI_MOSI */

    /* GPB 0 */
	{ EXYNOS5420_GPB0(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPB0(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPB0(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPB0(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* FUEL_SDA_1.8V */
	{ EXYNOS5420_GPB0(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* FUEL_SCL_1.8V */
    /* GPB 1 */
	{ EXYNOS5420_GPB1(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },	/* FPGA_SPI_SI */
	{ EXYNOS5420_GPB1(1), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },/* CODEC_SPI_SCK */
	{ EXYNOS5420_GPB1(2), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },/* CODEC_SPI_SS_N */
	{ EXYNOS5420_GPB1(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* CODEC_SPI_MISO */
	{ EXYNOS5420_GPB1(4), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },/* CODEC_SPI_MOSI */
    /* GPB 2 */
	{ EXYNOS5420_GPB2(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPB2(1), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE }, /* VIBTONE_PWM */
	{ EXYNOS5420_GPB2(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* AP_PMIC_SDA */
	{ EXYNOS5420_GPB2(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* AP_PMIC_SCL */
    /* GPB 3 */
	{ EXYNOS5420_GPB3(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* TSP_SDA_1.8V */
	{ EXYNOS5420_GPB3(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* TSP_SCL_1.8V */
	{ EXYNOS5420_GPB3(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPB3(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPB3(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* MEM_LDO_SDA */
	{ EXYNOS5420_GPB3(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* MEM_LDO_SCL */
	{ EXYNOS5420_GPB3(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* IF_PMIC_SDA */
	{ EXYNOS5420_GPB3(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* IF_PMIC_SCL */
    /* GPB 4 */
	{ EXYNOS5420_GPB4(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* MHL_SDA_1.8V */
	{ EXYNOS5420_GPB4(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* MHL_SCL_1.8V */
    /* GPC 0 */
	{ EXYNOS5420_GPC0(0), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* SDC1_CLK */
	{ EXYNOS5420_GPC0(1), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* SDC1_CMD */
	{ EXYNOS5420_GPC0(2), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* eMMC_EN */
	{ EXYNOS5420_GPC0(3), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* NAND_D(0) */
	{ EXYNOS5420_GPC0(4), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* NAND_D(1) */
	{ EXYNOS5420_GPC0(5), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* NAND_D(2) */
	{ EXYNOS5420_GPC0(6), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* NAND_D(3) */
	{ EXYNOS5420_GPC0(7), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* EMMC_RCLK */
    /* GPC 1 */
	{ EXYNOS5420_GPC1(0), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },/* WLAN_SDIO_CLK */
	{ EXYNOS5420_GPC1(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },	/* WLAN_SDIO_CMD */
	{ EXYNOS5420_GPC1(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* GPS_EN (NC for TD)*/
	{ EXYNOS5420_GPC1(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },	/* WLAN_SDIO_D(0) */
	{ EXYNOS5420_GPC1(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },	/* WLAN_SDIO_D(1) */
	{ EXYNOS5420_GPC1(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },	/* WLAN_SDIO_D(2) */
	{ EXYNOS5420_GPC1(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },	/* WLAN_SDIO_D(3) */
	{ EXYNOS5420_GPC1(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* NC */
    /* GPC 2 */
	{ EXYNOS5420_GPC2(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* T_FLASH_CLK */
	{ EXYNOS5420_GPC2(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* T_FLASH_CMD */
	{ EXYNOS5420_GPC2(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPC2(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* T_FLASH_D(0) */
	{ EXYNOS5420_GPC2(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* T_FLASH_D(1) */
	{ EXYNOS5420_GPC2(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* T_FLASH_D(2) */
	{ EXYNOS5420_GPC2(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* T_FLASH_D(3) */
    /* GPC 3 */
	{ EXYNOS5420_GPC3(0), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* NAND_D(4) */
	{ EXYNOS5420_GPC3(1), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* NAND_D(5) */
	{ EXYNOS5420_GPC3(2), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* NAND_D(6) */
	{ EXYNOS5420_GPC3(3), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* NAND_D(7) */
    /* GPC 4 */
	{ EXYNOS5420_GPC4(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPC4(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
    /* GPD 1 */
	{ EXYNOS5420_GPD1(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPD1(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
#if defined(CONFIG_KLIMT_WIFI) || defined(CONFIG_KLIMT_TD)
	{ EXYNOS5420_GPD1(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* MDM2AP_VDDMIN */
#else
	{ EXYNOS5420_GPD1(2), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE }, /* PDA_ACTIVE */
#endif
	{ EXYNOS5420_GPD1(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPD1(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* TOUCH_SDA */
	{ EXYNOS5420_GPD1(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* TOUCH_SCL */
	{ EXYNOS5420_GPD1(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPD1(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* OCTA_TE */

    /* GPE 0 */
	{ EXYNOS5420_GPE0(0), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* CAM_FLASH_EN */
	{ EXYNOS5420_GPE0(1), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* CAM_FLASH_SET */
	{ EXYNOS5420_GPE0(2), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },    /* CAM_VT_STBY */
	{ EXYNOS5420_GPE0(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPE0(4), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },    /* CAM_VT_nRST */
	{ EXYNOS5420_GPE0(5), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },    /* CAM_RESET */
	{ EXYNOS5420_GPE0(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPE0(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */

    /* GPE 1 */
	{ EXYNOS5420_GPE1(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* 8M_AVDD_LDO_EN */
	{ EXYNOS5420_GPE1(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
    /* GPF 0 */
	{ EXYNOS5420_GPF0(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* 8M_CAM_SDA_1.8V */
	{ EXYNOS5420_GPF0(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* 8M_CAM_SCL_1.8V */
	{ EXYNOS5420_GPF0(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* 8M_AF_SDA_1.8V */
	{ EXYNOS5420_GPF0(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* 8M_AF_SCL_1.8V */
	{ EXYNOS5420_GPF0(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* VT_CAM_SDA_1.8V */
	{ EXYNOS5420_GPF0(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* VT_CAM_SCL_1.8V */
    /* GPF 1 */
	{ EXYNOS5420_GPF1(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPF1(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPF1(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPF1(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPF1(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPF1(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPF1(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPF1(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
    /* GPG 0 */
	{ EXYNOS5420_GPG0(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPG0(1), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* CODEC_LDO_EN */
	{ EXYNOS5420_GPG0(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* CDONE */
	{ EXYNOS5420_GPG0(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* MHL_INT */
#if defined(CONFIG_KLIMT_3G) || defined(CONFIG_KLIMT_LTE)
	{ EXYNOS5420_GPG0(4), S5P_GPIO_PD_OUTPUT1, S5P_GPIO_PD_UPDOWN_DISABLE },/* CP_PMU_RST */
#elif defined(CONFIG_KLIMT_TD)	/* CP_PMU_RST */
	{ EXYNOS5420_GPG0(4), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* AP2MDM_PMIC_RESET_N */
#else
	{ EXYNOS5420_GPG0(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
#endif
	{ EXYNOS5420_GPG0(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* MICBIAS_EN */
	{ EXYNOS5420_GPG0(6), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* CODEC_RESET */
	{ EXYNOS5420_GPG0(7), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* BT_EN */
    /* GPG 1 */
#if defined(CONFIG_KLIMT_3G) || defined(CONFIG_KLIMT_LTE) || defined(CONFIG_KLIMT_TD)
	{ EXYNOS5420_GPG1(0), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE },/* IPC_SLAVE_WAKEUP */
#else
	{ EXYNOS5420_GPG1(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
#endif
	{ EXYNOS5420_GPG1(1), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* TSP_RST */
	{ EXYNOS5420_GPG1(2), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_DOWN_ENABLE },/* RESX */
#if defined(CONFIG_KLIMT_3G) || defined(CONFIG_KLIMT_LTE)
	{ EXYNOS5420_GPG1(3), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },   /* SUSPEND_REQUEST_HSIC */
	{ EXYNOS5420_GPG1(4), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },  /* CP_ON */
#elif defined(CONFIG_KLIMT_TD)
	{ EXYNOS5420_GPG1(3), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },   /* SUSPEND_REQUEST_HSIC */
	{ EXYNOS5420_GPG1(4), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE },   /* AP2MDM_PON_RESET_N */
#else
	{ EXYNOS5420_GPG1(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPG1(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
#endif
	{ EXYNOS5420_GPG1(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* ERR_FG */
#if defined(CONFIG_KLIMT_3G) || defined(CONFIG_KLIMT_LTE)
	{ EXYNOS5420_GPG1(6), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE },/* AP_DUMP_INT */
	{ EXYNOS5420_GPG1(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	   /* ACTIVE_STATE_HSIC */
#elif defined(CONFIG_KLIMT_TD)
	{ EXYNOS5420_GPG1(6), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* AP_DUMP_INT */
	{ EXYNOS5420_GPG1(7), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* AP2MDM_HSIC_PORT_ACTIVE */
#else
	{ EXYNOS5420_GPG1(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPG1(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
#endif
    /* GPG 2 */
	{ EXYNOS5420_GPG2(0), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* M_RST_N */
	{ EXYNOS5420_GPG2(1), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* CORE_MODE */
    /* GPH 0 */
	{ EXYNOS5420_GPH0(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* HW_REV0 */
	{ EXYNOS5420_GPH0(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* HW_REV1 */
	{ EXYNOS5420_GPH0(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* HW_REV2 */
	{ EXYNOS5420_GPH0(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* HW_REV3 */
	{ EXYNOS5420_GPH0(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* FPGA_SPI_CLK */
	{ EXYNOS5420_GPH0(5), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE }, /* CAM_MCLK */
	{ EXYNOS5420_GPH0(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* FPGA_SPI_EN */
	{ EXYNOS5420_GPH0(7), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE }, /* VTCAM_MCLK */
    /* GPJ 4 */
	{ EXYNOS5420_GPJ4(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* OCTA_TE */
#if defined(CONFIG_KLIMT_3G) || defined(CONFIG_KLIMT_LTE)
	{ EXYNOS5420_GPJ4(1), S5P_GPIO_PD_OUTPUT1, S5P_GPIO_PD_UPDOWN_DISABLE },/* RESET_REQ_N */
#elif defined(CONFIG_KLIMT_TD) 
	{ EXYNOS5420_GPJ4(1), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* AP2MDM_STATUS */
#else
	{ EXYNOS5420_GPJ4(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
#endif
	{ EXYNOS5420_GPJ4(2), S5P_GPIO_PD_OUTPUT1, S5P_GPIO_PD_UPDOWN_DISABLE }, /* CRESET_B */
	{ EXYNOS5420_GPJ4(3), S5P_GPIO_PD_OUTPUT1, S5P_GPIO_PD_UPDOWN_DISABLE }, /* MHL_RST */
    /* GPX 3 */
	{ EXYNOS5420_GPX3(6), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* SUB_MICBIAS_EN */
    /* GPY 0 */
	{ EXYNOS5420_GPY0(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY0(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, /* OCP_FLAG */
	{ EXYNOS5420_GPY0(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY0(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY0(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY0(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
    /* GPY 1 */
	{ EXYNOS5420_GPY1(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY1(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY1(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY1(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
    /* GPY 2 */
	{ EXYNOS5420_GPY2(0), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* TF_EN */
	{ EXYNOS5420_GPY2(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY2(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY2(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY2(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY2(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
    /* GPY 3 */
	{ EXYNOS5420_GPY3(0), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* MMC01_EN */
	{ EXYNOS5420_GPY3(1), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* MMC2_EN */
	{ EXYNOS5420_GPY3(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* MIPI_1.8V_EN */
	{ EXYNOS5420_GPY3(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY3(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY3(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY3(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY3(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
    /* GPY 4 */
	{ EXYNOS5420_GPY4(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY4(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY4(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY4(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY4(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY4(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY4(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY4(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
    /* GPY 5 */
	{ EXYNOS5420_GPY5(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY5(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY5(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY5(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY5(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY5(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY5(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY5(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
    /* GPY 6 */
	{ EXYNOS5420_GPY6(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY6(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY6(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY6(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY6(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY6(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY6(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
	{ EXYNOS5420_GPY6(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* NC */
    /* GPY 7 */
	{ EXYNOS5420_GPY7(0), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE }, /* 2M_A2.8V_EN */
	{ EXYNOS5420_GPY7(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* IRDA_IRQ */
	{ EXYNOS5420_GPY7(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* VT_CAM_ID */
	{ EXYNOS5420_GPY7(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, /* TA_INT */
	{ EXYNOS5420_GPY7(4), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* BTP_LDO_EN_3.3V */
	{ EXYNOS5420_GPY7(5), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* BTP_LDO_EN_1.8V */
	{ EXYNOS5420_GPY7(6), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* BTP_RST_N */
	{ EXYNOS5420_GPY7(7), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE }, /* WLAN_EN */

	/* GPX0 - GPX3 is alive part */
#if 0
	/*
	 * Accessing GPZ ports will crash when MAU power domain and clock are
	 * disabled
	 */
	{ EXYNOS5420_GPZ(0), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },
	{ EXYNOS5420_GPZ(1), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },
	{ EXYNOS5420_GPZ(2), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },
	{ EXYNOS5420_GPZ(3), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },
	{ EXYNOS5420_GPZ(4), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },
	{ EXYNOS5420_GPZ(5), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },
	{ EXYNOS5420_GPZ(6), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },
#endif
};

/* This funtion will be init breakpoint for GPIO verification */
void gpio_init_done(void)
{
	pr_info("%s\n", __func__);
#ifdef CONFIG_SEC_GPIO_DVS
	/************************ Caution !!! ****************************/
	/* This function must be located in appropriate INIT position
	 * in accordance with the specification of each BB vendor.
	 */
	/************************ Caution !!! ****************************/
	gpio_dvs_check_initgpio();
#endif
}

static void __init config_init_gpio(void)
{
	u32 i;

	for (i = 0; i < ARRAY_SIZE(init_gpio_table); i++) {
		u32 gpio = init_gpio_table[i].num;
		s3c_gpio_setpull(gpio, init_gpio_table[i].pud);
		s3c_gpio_cfgpin(gpio, init_gpio_table[i].cfg);

		if (init_gpio_table[i].cfg == S3C_GPIO_OUTPUT)
			gpio_set_value(gpio, init_gpio_table[i].val);
	}

	gpio_init_done();
}


static void config_sleep_gpio(struct gpio_sleep_data *table, u32 arr_size)
{
	u32 i;

	for (i = 0; i < arr_size; i++) {
		s5p_gpio_set_pd_pull(table[i].num, table[i].pud);
		s5p_gpio_set_pd_cfg(table[i].num, table[i].cfg);
	}
}

static void config_sleep_gpio_tables(void)
{
	int i;

	for (i = nr_klimt_sleep_gpio_table - 1; i >= 0; i--)
		config_sleep_gpio(klimt_sleep_gpio_tables[i].table,
				klimt_sleep_gpio_tables[i].arr_size);
}

void __init board_klimt_gpio_init(void)
{
	int i = 0;

	if (system_rev > MAX_BOARD_REV)
		panic("Invalid Board Revision: %d", system_rev);

    /* initialize init gpios */
	config_init_gpio();

    /* set function for sleep gpio config */
	switch (system_rev) {
	case 0:
		klimt_sleep_gpio_tables[i].table = sleep_gpio_table_rev00;
		klimt_sleep_gpio_tables[i].arr_size =
			ARRAY_SIZE(sleep_gpio_table_rev00);
		i++;
		/* Fall through */
	default:
		klimt_sleep_gpio_tables[i].table = sleep_gpio_table_latest;
		klimt_sleep_gpio_tables[i].arr_size =
			ARRAY_SIZE(sleep_gpio_table_latest);
		i++;
		break;
	}
	nr_klimt_sleep_gpio_table = i;

	exynos_config_sleep_gpio = config_sleep_gpio_tables;
}
